version: '3.8'

services:
  replication_postgres:
    image: postgres
    container_name: replication_postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./postgres.conf:/etc/postgresql/postgresql.conf"
      - "pgdata:/var/lib/postgresql/data"
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

  redis_stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - "redisdata:/data"

volumes:
  pgdata:
  redisdata:
